language: cpp
dist: xenial
env: 
  - CXX_EXE=/usr/bin/g++-7 CC_EXE=/usr/bin/gcc-7 GCOV=/usr/bin/gcov-7 CMAKE_OPTIONS="-DENABLE_COVERAGE:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - libx11-dev
      - libxrandr-dev
      - libudev-dev
      - g++-7
      - boost1.68
      - libgtest-dev

install:
  - sudo -H pip install coverage

script:
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - mkdir -p build && cd build
  - cmake $CMAKE_OPTIONS ..
  - make -j4
  - ctest .
  - bash <(curl -s https://codecov.io/bash) -x $GCOV
